# Global settings for Netlify
[build]
  command = "cd stage-2/movie-discovery-app && npm run build"  # build command if applicable

# Publish settings for stage one task
[[redirects]]
  from = "/Stage-1/*"       # Define the URL path for stage one task
  to = "/Stage-1"     # Specify the directory path for stage one task
  status = 200
  publish = "Stage-1"       # Specify the directory to publish for stage one task

# Publish settings for Wall-clock
[[redirects]]
  from = "/stage-2/*"           # Define the URL path for Wall-clock
  to = "/stage-2/:splat"         # Specify the directory path for Wall-clock
  status = 200
  publish = "stage-2/movie-discovery-app/build"  # Specify the directory to publish for Wall-clock
