# Global settings for Netlify
[build]
  command = "npm run build"  # build command if applicable

[[redirects]]
  from = "/image-gallery/*"
  to = "/image-gallery/:splat"     
  status = 200
  publish = "build"

# Publish settings for stage one task
[[redirects]]
  from = "/Stage-1/*"       # Define the URL path for stage one task
  to = "/Stage-1"     # Specify the directory path for stage one task
  status = 200
  publish = "Stage-1"       # Specify the directory to publish for stage one task

